### PR TITLE
feat: Chunk requests in loaders

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by jquense** [comment]
This isn't about over long urls? Is chunking enough, should we try for something more related to urls length? To much?

**Comment by taion** [comment]
This code got lost in the merge :p It's been working fine otherwise.

It's tricky to do this in URL generation, because `getPath` wouldn't know where to split.

Also, it's not _strictly_ the URL length. It's the combination of URL + headers + whatever, often subject to cruft like uWSGI including the query string twice in its buffers.

**Comment by jquense** [comment]
fair enough LGTM

**Comment by taion** [comment]
oh i should fix the commit comment eh

**Pull request merged**
