### PR TITLE
Update request options type

### PR DESCRIPTION
**Pull request by AaronBuxbaum**
Allows us to pass previously unsupported fetch init attributes

### CODE REVIEW

**Comment by taion** [comment]
CI failing here btw

**Comment by AaronBuxbaum** [comment]
> CI failing here btw

Yep, I'm fixing the types here, should be done soon hopefully

**Comment by AaronBuxbaum** [comment]
So here's something unusual -- the type overrides for tests affect the types elsewhere. Not sure why, but /shrug

**Comment by AaronBuxbaum** [comment]
@taion can you cut a new version? I don't have npm access in 4C

**Comment by taion** [comment]
You weren't supposed to need it. The issue is that this PR was missing the semantic commit tag.

**Pull request merged**
